Verify page moved tags under approve
Greenstand/treetracker-admin pull request #320
Opened 2020-07-22 04:22 UTC by ericlvogt

Moved tags under approve there should be no confusion now.
![image](https://user-images.githubusercontent.com/63984391/88133901-7072d080-cba0-11ea-99cb-68b41f3fca45.png)

2020-08-04 01:14 UTC, dadiorchen commented
@Davidezrajay Do you think this change is reasonable?  Comparing what we have currently:

![image](https://user-images.githubusercontent.com/5744708/89241928-d7799600-d632-11ea-8c51-416d31d8b7db.png)

Move the tag and species port into the section of 'approve'.

2020-08-08 21:46 UTC, ericlvogt commented
Forgot to link the issue before. This PR addresses issue #300 to prevent confusion of what is saved on submit. On reject submit only the reject reason is saved therefore all other tags have been moved under approve.

2020-08-12 06:10 UTC, dadiorchen commented
@Davidezrajay what's you thoughts on this?

2020-09-08 18:23 UTC, nmcharlton requested changes, later dismissed
Sorry for the long delay in reviewing.

2020-09-08 18:23 UTC, nmcharlton commented on client/src/components/TreeImageScrubber.js
> +                <Typography variant='h6' >Tags</Typography>
I think this title should be above the tabs as it applies to both approval and rejection

2020-09-08 18:38 UTC, nmcharlton commented on client/src/components/TreeImageScrubber.js
> +                <Typography variant='h6' >Tags</Typography>
Scrap that - it's fine as it is.

2021-02-20 03:33 UTC, TANguyen1893 commented
Any further development should be done in the admin panel client repo: https://github.com/Greenstand/treetracker-admin-client

2021-02-21 09:19 UTC, closed without merging