Milestone1
Greenstand/treetracker-admin pull request #547
Opened 2021-04-07 22:05 UTC by arunbakt

2021-04-08 02:13 UTC, dadiorchen approved these changes

2021-04-08 08:05 UTC, nmcharlton commented
@arunbakt Can you pull the latest master branch to get the refactored kustomize yaml files?
This change will need to go in `deployment/overlays/development/treetracker-dev-rabbitmq-sealedsecret.yaml`

2021-04-08 08:06 UTC, nmcharlton requested changes
@arunbakt Can you pull the latest master branch to get the refactored kustomize yaml files?
This change will need to go in `deployment/overlays/development/treetracker-dev-rabbitmq-sealedsecret.yaml`

2021-04-30 19:57 UTC, nmcharlton approved these changes

2021-04-30 20:20 UTC, merged