feat: add device_identifier to planter_registration model
Greenstand/treetracker-admin pull request #592
Opened 2021-09-24 13:55 UTC by tranquanghuy0801

Resolves #532

2021-09-24 20:14 UTC, nmcharlton requested changes

2021-09-24 20:14 UTC, nmcharlton commented on src/models/planterRegistration.model.ts
> +  deviceIdentifier?: Number;
This should be a `string`

2021-09-25 01:23 UTC, dadiorchen approved these changes

2021-09-25 06:27 UTC, nmcharlton approved these changes

2021-09-25 06:27 UTC, merged